### ISSUE TITLE
Bad arguments to http.client.HTTPConnection

### ISSUE THREAD

**Issue by MatthewLM** [massanchik/bitcoin-python3#2]
Hi, I tried this out but there should not be the False argument to http.client.HTTPConnection in proxy.py (See documentation: https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse). There might be other problems. I'm considering whether I should try to fix this or use some other solution for Bitcoin rpc commands in python 3. If I do get it working I can submit a pull request.

**Comment by massanchik** [comment]
Hi! Thank you for your contribution. 
bitcoin-python3 library is ported from [laanwj/bitcoin-python](https://github.com/laanwj/bitcoin-python) with 2to3 tool.
So if you find any 2to3 specific issues, then I can commit fixes. Other bugs/errors should be reported to [original repo](https://github.com/laanwj/bitcoin-python)
